V1190 Demo: console.h File Reference
console.h File Reference
Defines
#define ulong unsigned long
#define uint unsigned int
#define ushort unsigned short
#define uchar unsigned char
#define CR 0x0D
#define BLANK 0x20
#define ESC 0x1B
#define BSP 0x08
#define TERM_NOT_INIT FALSE
#define TERM_INIT TRUE
Functions
void con_init (void)
void con_end (void)
int write_log (char *)
int con_getch (void)
char con_kbhit (void)
int con_scanf (char *, void *)
int con_printf (const char *,...)
void gotoxy (int, int)
int con_printf_xy (uint, uint, char *,...)
void clrscr (void)
void clear_line (uint)
void delay (int)
Define Documentation
#define BLANK 0x20
Definition at line 72 of file console.h.
#define BSP 0x08
Definition at line 74 of file console.h.
#define CR 0x0D
Definition at line 71 of file console.h.
#define ESC 0x1B
Definition at line 73 of file console.h.
#define TERM_INIT TRUE
Definition at line 78 of file console.h.
Referenced by con_init().
#define TERM_NOT_INIT FALSE
Definition at line 77 of file console.h.
#define uchar unsigned char
Definition at line 63 of file console.h.
#define uint unsigned int
Definition at line 57 of file console.h.
#define ulong unsigned long
Definition at line 54 of file console.h.
#define ushort unsigned short
Definition at line 60 of file console.h.
Function Documentation
void clear_line (uint)
Definition at line 434 of file console.c.
References gotoxy(), and ocon.
void clrscr (void)
Definition at line 390 of file console.c.
References ocon.
Referenced by con_init(), and user_settings_parse_input_param().
void con_end (void)
Definition at line 130 of file console.c.
Referenced by main().
int con_getch (void)
Definition at line 175 of file console.c.
Referenced by con_kbhit(), and main().
void con_init (void)
Definition at line 86 of file console.c.
References clrscr(), icon, ocon, t_type, and TERM_INIT.
Referenced by main().
char con_kbhit (void)
Definition at line 203 of file console.c.
References con_getch().
Referenced by con_scanf(), main(), and user_settings_parse_input_param().
int con_printf (const char * , ...)
Definition at line 278 of file console.c.
Referenced by main().
int con_printf_xy (uint , uint , char * , ...)
Definition at line 348 of file console.c.
References gotoxy().
int con_scanf (char * , void *)
Definition at line 239 of file console.c.
References con_kbhit().
void delay (int)
Definition at line 482 of file console.c.
void gotoxy (int , int)
Definition at line 317 of file console.c.
References ocon.
Referenced by clear_line(), and con_printf_xy().
int write_log (char *)
Definition at line 149 of file console.c.
References log_file, and LOG_FILE_NAME.