V1190 Demo: main.c File Reference
main.c File Reference
#include <stdlib.h>
#include <stdio.h>
#include <stdarg.h>
#include "common_defs.h"
#include "../include/CAENVMETool/cvt_board_commons.h"
#include "../include/CAENVMETool/cvt_common_defs.h"
#include "../include/CAENVMETool/cvt_V1190.h"
#include "user_settings.h"
#include "console.h"
Defines
#define GLB_HDR_STR "GLB_HDR - EVT COUNT : %08x GEO : %08x \n"
#define GLB_TRL_STR "GLB_TRL - STATUS : %08x WCOUNT : %08x GEO : %08x \n"
#define TDC_HDR_STR " TDC_HDR - TDC : %08x EVT ID : %08x BUNCH ID: %08x \n"
#define TDC_MSR_STR " TDC_MSR - TRAILING : %08x CH : %08x MEASURE : %08x \n"
#define TDC_ERR_STR " TDC_ERR - TDC : %08x ERR FLAGS: %08x \n"
#define TDC_TRL_STR " TDC_TRL - TDC : %08x EVT ID : %08x WCOUNT : %08x \n"
#define TDC_TRG_STR " TDC_TRG - TRG TIME TAG: %08x \n"
#define FILLER_STR " FILLER - \n"
#define UNKNOWN_STR "\n??? UNKNOWN TAG ??? - READ WORD: %08x \n\n"
Functions
int main (int argc, char **argv)
CAENVMETool demo usage for the V1190 board.
Define Documentation
#define FILLER_STR " FILLER - \n"
Definition at line 40 of file main.c.
Referenced by main().
#define GLB_HDR_STR "GLB_HDR - EVT COUNT : %08x GEO : %08x \n"
Definition at line 33 of file main.c.
Referenced by main().
#define GLB_TRL_STR "GLB_TRL - STATUS : %08x WCOUNT : %08x GEO : %08x \n"
Definition at line 34 of file main.c.
Referenced by main().
#define TDC_ERR_STR " TDC_ERR - TDC : %08x ERR FLAGS: %08x \n"
Definition at line 37 of file main.c.
Referenced by main().
#define TDC_HDR_STR " TDC_HDR - TDC : %08x EVT ID : %08x BUNCH ID: %08x \n"
Definition at line 35 of file main.c.
Referenced by main().
#define TDC_MSR_STR " TDC_MSR - TRAILING : %08x CH : %08x MEASURE : %08x \n"
Definition at line 36 of file main.c.
Referenced by main().
#define TDC_TRG_STR " TDC_TRG - TRG TIME TAG: %08x \n"
Definition at line 39 of file main.c.
Referenced by main().
#define TDC_TRL_STR " TDC_TRL - TDC : %08x EVT ID : %08x WCOUNT : %08x \n"
Definition at line 38 of file main.c.
Referenced by main().
#define UNKNOWN_STR "\n??? UNKNOWN TAG ??? - READ WORD: %08x \n\n"
Definition at line 41 of file main.c.
Referenced by main().
Function Documentation
int main (int argc, char ** argv)
CAENVMETool demo usage for the V1190 board.
Setups a V1190 board, reads some events and stores into output file
Parameters:
argc number of command line arguments
*argv[] command line arguments' list
Returns:
= 0 procedure completed correctly: < 0 some error occurred
Definition at line 70 of file main.c.
References AM_CONTINUOUS, AM_NONE, AM_TRIGGER_MATCH, con_end(), con_getch(), con_init(), con_kbhit(), con_printf(), FILLER_STR, GLB_HDR_STR, GLB_TRL_STR, user_setting_data::m_acquisition_mode, user_setting_data::m_base_address, user_setting_data::m_board_number, user_setting_data::m_board_type, acquisition_mode::m_continuos, trigger_matching_mode_param::m_edge_detection, continuous_mode_param::m_edge_detection, trigger_matching_mode_param::m_empty_event_enable, trigger_matching_mode_param::m_enable_msk, continuous_mode_param::m_enable_msk, trigger_matching_mode_param::m_extra_search_margin, trigger_matching_mode_param::m_header_trailer_enable, user_setting_data::m_link_number, acquisition_mode::m_mode, user_setting_data::m_num_events, acquisition_mode::m_params, user_setting_data::m_parsed_output_filename, user_setting_data::m_raw_output_filename, trigger_matching_mode_param::m_reject_margin, trigger_matching_mode_param::m_res_width, continuous_mode_param::m_res_width, user_setting_data::m_tdc_count, acquisition_mode::m_trigger_matching, trigger_matching_mode_param::m_trigger_time_tag_enable, user_setting_data::m_V1190_type, trigger_matching_mode_param::m_window_offset, trigger_matching_mode_param::m_window_width, MAX_V1190_TDC_COUNT, TDC_ERR_STR, TDC_HDR_STR, TDC_MSR_STR, TDC_TRG_STR, TDC_TRL_STR, TRACE, TRACE1, TRACE2, UNKNOWN_STR, user_settings_close(), user_settings_open(), and user_settings_parse_input_param().