V1190 Demo: user_settings.c File Reference
user_settings.c File Reference
#include <malloc.h>
#include <stdlib.h>
#include <string.h>
#include "common_defs.h"
#include "user_settings.h"
Defines
#define DEF_RAW_OUTPUT_FILENAME "raw_values.dat"
#define DEF_PARSED_OUTPUT_FILENAME "parsed_values.dat"
#define MAX_FILENAME_LENGHT 255
#define DEF_NUM_EVENTS -1
#define DEF_BASE_ADDRESS 0x3210
#define DEF_BOARD_TYPE_STR "V1190A"
#define DEF_V1190_TYPE CVT_V1190_TYPE_A
#define DEF_TDC_COUNT CVT_V1190_NUM_TDC_A
#define DEF_ACQUISITION_MODE AM_TRIGGER_MATCH
#define DEF_ACQUISITION_MODE_PARAMS "1,1,0,-1,-1,-1,-1,1,0"
Functions
static BOOL parse_continuous_param (const char *line, continuous_mode_param *target)
static BOOL parse_trigger_matching_param (const char *line, trigger_matching_mode_param *target)
BOOL user_settings_open (user_setting_data *p_data)
init user setting module
BOOL user_settings_close (user_setting_data *p_data)
closes user setting module (frees allocated resources)
BOOL user_settings_parse_input_param (user_setting_data *p_data, int argc, char *argv[])
Scan<s user input parameters.
Define Documentation
#define DEF_ACQUISITION_MODE AM_TRIGGER_MATCH
Default acquisition mode
Definition at line 33 of file user_settings.c.
Referenced by user_settings_open().
#define DEF_ACQUISITION_MODE_PARAMS "1,1,0,-1,-1,-1,-1,1,0"
Default acquisition mode params
Definition at line 34 of file user_settings.c.
Referenced by user_settings_open(), and user_settings_parse_input_param().
#define DEF_BASE_ADDRESS 0x3210
Default boards' base address
Definition at line 29 of file user_settings.c.
Referenced by user_settings_open(), and user_settings_parse_input_param().
#define DEF_BOARD_TYPE_STR "V1190A"
Default V1190's type string
Definition at line 30 of file user_settings.c.
Referenced by user_settings_parse_input_param().
#define DEF_NUM_EVENTS -1
Default number of events
Definition at line 28 of file user_settings.c.
Referenced by user_settings_open(), and user_settings_parse_input_param().
#define DEF_PARSED_OUTPUT_FILENAME "parsed_values.dat"
Parsed board values default filename
Definition at line 24 of file user_settings.c.
Referenced by user_settings_open(), and user_settings_parse_input_param().
#define DEF_RAW_OUTPUT_FILENAME "raw_values.dat"
Raw board values default filename
Definition at line 23 of file user_settings.c.
Referenced by user_settings_open(), and user_settings_parse_input_param().
#define DEF_TDC_COUNT CVT_V1190_NUM_TDC_A
Default V1190 number of TDCs
Definition at line 32 of file user_settings.c.
Referenced by user_settings_open().
#define DEF_V1190_TYPE CVT_V1190_TYPE_A
Default V1190's type
Definition at line 31 of file user_settings.c.
Referenced by user_settings_open().
#define MAX_FILENAME_LENGHT 255
Maximum filenam length
Definition at line 26 of file user_settings.c.
Referenced by user_settings_open().
Function Documentation
BOOL parse_continuous_param (const char * line, continuous_mode_param * target) [static]
Definition at line 327 of file user_settings.c.
References continuous_mode_param::m_edge_detection, continuous_mode_param::m_enable_msk, continuous_mode_param::m_res_width, and MAX_CH_ENABLE_WORD.
Referenced by user_settings_open(), and user_settings_parse_input_param().
BOOL parse_trigger_matching_param (const char * line, trigger_matching_mode_param * target) [static]
Definition at line 366 of file user_settings.c.
References trigger_matching_mode_param::m_edge_detection, trigger_matching_mode_param::m_empty_event_enable, trigger_matching_mode_param::m_enable_msk, trigger_matching_mode_param::m_extra_search_margin, trigger_matching_mode_param::m_header_trailer_enable, trigger_matching_mode_param::m_reject_margin, trigger_matching_mode_param::m_res_width, trigger_matching_mode_param::m_trigger_time_tag_enable, trigger_matching_mode_param::m_window_offset, trigger_matching_mode_param::m_window_width, and MAX_CH_ENABLE_WORD.
Referenced by user_settings_open(), and user_settings_parse_input_param().
BOOL user_settings_close (user_setting_data * p_data)
closes user setting module (frees allocated resources)
Parameters:
*p_data data buffer pointer
Returns:
TRUE procedure completed correctly
Note:
call after any other methods
Definition at line 90 of file user_settings.c.
References user_setting_data::m_parsed_output_filename, and user_setting_data::m_raw_output_filename.
Referenced by main().
BOOL user_settings_open (user_setting_data * p_data)
init user setting module
Parameters:
*p_data data buffer pointer
Returns:
TRUE procedure completed correctly
Note:
call before any other methods
Definition at line 52 of file user_settings.c.
References AM_CONTINUOUS, AM_NONE, AM_TRIGGER_MATCH, DEF_ACQUISITION_MODE, DEF_ACQUISITION_MODE_PARAMS, DEF_BASE_ADDRESS, DEF_NUM_EVENTS, DEF_PARSED_OUTPUT_FILENAME, DEF_RAW_OUTPUT_FILENAME, DEF_TDC_COUNT, DEF_V1190_TYPE, user_setting_data::m_acquisition_mode, user_setting_data::m_base_address, acquisition_mode::m_continuos, acquisition_mode::m_mode, user_setting_data::m_num_events, acquisition_mode::m_params, user_setting_data::m_parsed_output_filename, user_setting_data::m_raw_output_filename, user_setting_data::m_tdc_count, acquisition_mode::m_trigger_matching, user_setting_data::m_V1190_type, MAX_FILENAME_LENGHT, parse_continuous_param(), parse_trigger_matching_param(), and TRACE.
Referenced by main().
BOOL user_settings_parse_input_param (user_setting_data * p_data, int argc, char * argv[])
Scan<s user input parameters.
Parameters:
*p_data data buffer pointer
argc number of input parameters
*argv[] string parameters list
Returns:
TRUE procedure completed correctly
Definition at line 107 of file user_settings.c.
References AM_CONTINUOUS, AM_TRIGGER_MATCH, clrscr(), con_kbhit(), DEF_ACQUISITION_MODE_PARAMS, DEF_BASE_ADDRESS, DEF_BOARD_TYPE_STR, DEF_NUM_EVENTS, DEF_PARSED_OUTPUT_FILENAME, DEF_RAW_OUTPUT_FILENAME, user_setting_data::m_acquisition_mode, user_setting_data::m_base_address, acquisition_mode::m_continuos, acquisition_mode::m_mode, user_setting_data::m_num_events, acquisition_mode::m_params, user_setting_data::m_parsed_output_filename, user_setting_data::m_raw_output_filename, user_setting_data::m_tdc_count, acquisition_mode::m_trigger_matching, user_setting_data::m_V1190_type, MAX_CH_ENABLE_WORD, MAX_V1190_TDC_COUNT, parse_continuous_param(), parse_trigger_matching_param(), TRACE, and TRACE1.
Referenced by main().