V1190 Demo: user_settings.h File Reference
user_settings.h File Reference
#include "common_defs.h"
#include "../include/CAENVMETool/cvt_board_commons.h"
#include "../include/CAENVMETool/cvt_common_defs.h"
#include "../include/CAENVMETool/cvt_V1190.h"
Data Structures
struct trigger_matching_mode_param
Trigger matching acquisition mode parameters.
struct continuous_mode_param
Continuous acquisition mode parameters.
struct acquisition_mode
The acquisition mode parameters.
struct user_setting_data
User settings data structure.
Defines
#define MAX_V1190_TDC_COUNT CVT_V1190_NUM_TDC_A
#define MAX_V1190_CH_PER_TDC_COUNT CVT_V1190_CH_PER_TDC
#define MAX_CH_ENABLE_WORD ((MAX_V1190_TDC_COUNT* MAX_V1190_CH_PER_TDC_COUNT)>> 4)
Enumerations
enum ACQUISITION_MODES { AM_NONE, AM_CONTINUOUS, AM_TRIGGER_MATCH }
The acquisition mode enumeration.
Functions
BOOL user_settings_open (user_setting_data *p_data)
init user setting module
BOOL user_settings_close (user_setting_data *p_data)
closes user setting module (frees allocated resources)
BOOL user_settings_parse_input_param (user_setting_data *p_data, int argc, char *argv[])
Scan<s user input parameters.
Define Documentation
#define MAX_CH_ENABLE_WORD ((MAX_V1190_TDC_COUNT* MAX_V1190_CH_PER_TDC_COUNT)>> 4)
Definition at line 27 of file user_settings.h.
Referenced by parse_continuous_param(), parse_trigger_matching_param(), and user_settings_parse_input_param().
#define MAX_V1190_CH_PER_TDC_COUNT CVT_V1190_CH_PER_TDC
Maximun number of V1190's channels per TDC
Definition at line 26 of file user_settings.h.
#define MAX_V1190_TDC_COUNT CVT_V1190_NUM_TDC_A
Maximun number of V1190's TDCs
Definition at line 25 of file user_settings.h.
Referenced by main(), and user_settings_parse_input_param().
Enumeration Type Documentation
enum ACQUISITION_MODES
The acquisition mode enumeration.
Enumerator:
AM_NONE No settings for acquisition mode.
AM_CONTINUOUS Continuous acquisition mode.
AM_TRIGGER_MATCH Trigger match acquisition mode.
Definition at line 69 of file user_settings.h.
Function Documentation
BOOL user_settings_close (user_setting_data * p_data)
closes user setting module (frees allocated resources)
Parameters:
*p_data data buffer pointer
Returns:
TRUE procedure completed correctly
Note:
call after any other methods
Definition at line 90 of file user_settings.c.
References user_setting_data::m_parsed_output_filename, and user_setting_data::m_raw_output_filename.
Referenced by main().
BOOL user_settings_open (user_setting_data * p_data)
init user setting module
Parameters:
*p_data data buffer pointer
Returns:
TRUE procedure completed correctly
Note:
call before any other methods
Definition at line 52 of file user_settings.c.
References AM_CONTINUOUS, AM_NONE, AM_TRIGGER_MATCH, DEF_ACQUISITION_MODE, DEF_ACQUISITION_MODE_PARAMS, DEF_BASE_ADDRESS, DEF_NUM_EVENTS, DEF_PARSED_OUTPUT_FILENAME, DEF_RAW_OUTPUT_FILENAME, DEF_TDC_COUNT, DEF_V1190_TYPE, user_setting_data::m_acquisition_mode, user_setting_data::m_base_address, acquisition_mode::m_continuos, acquisition_mode::m_mode, user_setting_data::m_num_events, acquisition_mode::m_params, user_setting_data::m_parsed_output_filename, user_setting_data::m_raw_output_filename, user_setting_data::m_tdc_count, acquisition_mode::m_trigger_matching, user_setting_data::m_V1190_type, MAX_FILENAME_LENGHT, parse_continuous_param(), parse_trigger_matching_param(), and TRACE.
Referenced by main().
BOOL user_settings_parse_input_param (user_setting_data * p_data, int argc, char * argv[])
Scan<s user input parameters.
Parameters:
*p_data data buffer pointer
argc number of input parameters
*argv[] string parameters list
Returns:
TRUE procedure completed correctly
Definition at line 107 of file user_settings.c.
References AM_CONTINUOUS, AM_TRIGGER_MATCH, clrscr(), con_kbhit(), DEF_ACQUISITION_MODE_PARAMS, DEF_BASE_ADDRESS, DEF_BOARD_TYPE_STR, DEF_NUM_EVENTS, DEF_PARSED_OUTPUT_FILENAME, DEF_RAW_OUTPUT_FILENAME, user_setting_data::m_acquisition_mode, user_setting_data::m_base_address, acquisition_mode::m_continuos, acquisition_mode::m_mode, user_setting_data::m_num_events, acquisition_mode::m_params, user_setting_data::m_parsed_output_filename, user_setting_data::m_raw_output_filename, user_setting_data::m_tdc_count, acquisition_mode::m_trigger_matching, user_setting_data::m_V1190_type, MAX_CH_ENABLE_WORD, MAX_V1190_TDC_COUNT, parse_continuous_param(), parse_trigger_matching_param(), TRACE, and TRACE1.
Referenced by main().