/////////////////////////////////////////////////////////////////////////////
// Name:        trash.h
// Purpose:     
// Author:      NDA
// Modified by: 
// Created:     23/10/2010 19:13:48
// RCS-ID:      
// Copyright:   CAEN S.p.A All rights reserved.
// Licence:     
/////////////////////////////////////////////////////////////////////////////

// Generated by DialogBlocks (unregistered), 23/10/2010 19:13:48

#ifndef _TRASH_H_
#define _TRASH_H_

#if defined(__GNUG__) && !defined(NO_GCC_PRAGMA)
#pragma interface "trash.h"
#endif

/*!
 * Includes
 */

////@begin includes
////@end includes

/*!
 * Forward declarations
 */

////@begin forward declarations
////@end forward declarations

/*!
 * Control identifiers
 */

////@begin control identifiers
#define ID_DIALOG 10022
#define SYMBOL_TRASH_STYLE wxCAPTION|wxRESIZE_BORDER|wxSYSTEM_MENU|wxCLOSE_BOX
#define SYMBOL_TRASH_TITLE _("Trash")
#define SYMBOL_TRASH_IDNAME ID_DIALOG
#define SYMBOL_TRASH_SIZE wxSize(400, 300)
#define SYMBOL_TRASH_POSITION wxDefaultPosition
#define ID_PANEL 10024
#define ID_GRID_LINE_TYPE_CHOICE 10025
#define ID_CHECKBOX1 10039
#define ID_CHECKLISTBOX1 10092
////@end control identifiers

/*!
 * Compatibility
 */

#ifndef wxCLOSE_BOX
#define wxCLOSE_BOX 0x1000
#endif

/*!
 * Trash class declaration
 */

class Trash: public wxDialog
{    
    DECLARE_DYNAMIC_CLASS( Trash )
    DECLARE_EVENT_TABLE()

public:
    /// Constructors
    Trash( );
    Trash( wxWindow* parent, wxWindowID id = SYMBOL_TRASH_IDNAME, const wxString& caption = SYMBOL_TRASH_TITLE, const wxPoint& pos = SYMBOL_TRASH_POSITION, const wxSize& size = SYMBOL_TRASH_SIZE, long style = SYMBOL_TRASH_STYLE );

    /// Creation
    bool Create( wxWindow* parent, wxWindowID id = SYMBOL_TRASH_IDNAME, const wxString& caption = SYMBOL_TRASH_TITLE, const wxPoint& pos = SYMBOL_TRASH_POSITION, const wxSize& size = SYMBOL_TRASH_SIZE, long style = SYMBOL_TRASH_STYLE );

    /// Creates the controls and sizers
    void CreateControls();

////@begin Trash event handler declarations

////@end Trash event handler declarations

////@begin Trash member function declarations

    /// Retrieves bitmap resources
    wxBitmap GetBitmapResource( const wxString& name );

    /// Retrieves icon resources
    wxIcon GetIconResource( const wxString& name );
////@end Trash member function declarations

    /// Should we show tooltips?
    static bool ShowToolTips();

////@begin Trash member variables
    wxChoice* m_grid_line_type_control;
////@end Trash member variables
};

#endif
    // _TRASH_H_
