/////////////////////////////////////////////////////////////////////////////
// Name:        virtual_common_ch_control.h
// Purpose:     
// Author:      NDA
// Modified by: 
// Created:     11/01/2007 15:09:38
// RCS-ID:      
// Copyright:   CAEN S.p.A All rights reserved.
// Licence:     
/////////////////////////////////////////////////////////////////////////////

// Generated by DialogBlocks (unregistered), 11/01/2007 15:09:38

#ifndef _VIRTUAL_COMMON_CH_CONTROL_H_
#define _VIRTUAL_COMMON_CH_CONTROL_H_

#if defined(__GNUG__) && !defined(NO_GCC_PRAGMA)
#pragma interface "virtual_common_ch_control.h"
#endif

/*!
 * Includes
 */

////@begin includes
#include "wx/tglbtn.h"
////@end includes

#include "generic_board.h"
#include "virtual_board_channel.h"
#include "common_ch_control_base.h"

/*!
 * Forward declarations
 */

////@begin forward declarations
class wxToggleButton;
////@end forward declarations

/*!
 * Control identifiers
 */

////@begin control identifiers
#define ID_VIRTUAL_COMMON_CH_DIALOG 11030
#define SYMBOL_VIRTUALCOMMONCHCONTROL_STYLE 0
#define SYMBOL_VIRTUALCOMMONCHCONTROL_TITLE _("VirtualCommonChControl")
#define SYMBOL_VIRTUALCOMMONCHCONTROL_IDNAME ID_VIRTUAL_COMMON_CH_DIALOG
#define SYMBOL_VIRTUALCOMMONCHCONTROL_SIZE wxDefaultSize
#define SYMBOL_VIRTUALCOMMONCHCONTROL_POSITION wxDefaultPosition
#define ID_VIRTUAL_ENABLE_TOGGLEBUTTON 10000
#define ID_VIRTUAL_BUTTON 10083
////@end control identifiers

/*!
 * Compatibility
 */

#ifndef wxCLOSE_BOX
#define wxCLOSE_BOX 0x1000
#endif

/*!
 * VirtualCommonChControl class declaration
 */

class VirtualCommonChControl: public CommonChControlBase
{    
    DECLARE_DYNAMIC_CLASS( VirtualCommonChControl )
    DECLARE_EVENT_TABLE()

public:
    /// Constructors
    VirtualCommonChControl( );
	VirtualCommonChControl( wxWindow* parent, wxWindowID id = SYMBOL_VIRTUALCOMMONCHCONTROL_IDNAME, const wxPoint& pos = SYMBOL_VIRTUALCOMMONCHCONTROL_POSITION, const wxSize& size = SYMBOL_VIRTUALCOMMONCHCONTROL_SIZE, long style = SYMBOL_VIRTUALCOMMONCHCONTROL_STYLE );

    /// Creation
    bool Create( wxWindow* parent, wxWindowID id = SYMBOL_VIRTUALCOMMONCHCONTROL_IDNAME, const wxPoint& pos = SYMBOL_VIRTUALCOMMONCHCONTROL_POSITION, const wxSize& size = SYMBOL_VIRTUALCOMMONCHCONTROL_SIZE, long style = SYMBOL_VIRTUALCOMMONCHCONTROL_STYLE );

    /// Creates the controls and sizers
    void CreateControls();

////@begin VirtualCommonChControl event handler declarations

    /// wxEVT_COMMAND_CHECKBOX_CLICKED event handler for ID_VIRTUAL_ENABLE_TOGGLEBUTTON
    void OnVirtualEnableTogglebuttonClick( wxCommandEvent& event );

    /// wxEVT_COMMAND_BUTTON_CLICKED event handler for ID_VIRTUAL_BUTTON
    void OnVirtualButtonClick( wxCommandEvent& event );

////@end VirtualCommonChControl event handler declarations

////@begin VirtualCommonChControl member function declarations

    /// Retrieves bitmap resources
    wxBitmap GetBitmapResource( const wxString& name );

    /// Retrieves icon resources
    wxIcon GetIconResource( const wxString& name );
////@end VirtualCommonChControl member function declarations

    /// Should we show tooltips?
    static bool ShowToolTips();

////@begin VirtualCommonChControl member variables
    wxStaticBox* m_main_sizer_text;
    wxToggleButton* m_ch_enable_control;
    wxStaticText* m_medium_value_control;
////@end VirtualCommonChControl member variables

	bool SetupBoard( GenericBoard* p_board, int ch_index, int ch_count);
	bool UpdateControls( );
	void SetMediumLabel( double value);
	void SetOverloadBackground( const wxColor& color);

private: 
	// Generic Board pointer
	GenericBoard* m_p_board;
	VirtualBoardChannel* m_p_board_channel;
	int m_ch_index;
	int m_ch_count;
};

#endif
    // _VIRTUAL_COMMON_CH_CONTROL_H_
