/////////////////////////////////////////////////////////////////////////////
// Name:        virtual_channel_def_dialog.h
// Purpose:     
// Author:      NDA
// Modified by: 
// Created:     10/01/2007 12:50:38
// RCS-ID:      
// Copyright:   CAEN S.p.A All rights reserved.
// Licence:     
/////////////////////////////////////////////////////////////////////////////

// Generated by DialogBlocks (unregistered), 10/01/2007 12:50:38

#ifndef _VIRTUAL_CHANNEL_DEF_DIALOG_H_
#define _VIRTUAL_CHANNEL_DEF_DIALOG_H_

#if defined(__GNUG__) && !defined(NO_GCC_PRAGMA)
#pragma interface "virtual_channel_def_dialog.h"
#endif

/*!
 * Includes
 */

////@begin includes
#include "wx/spinctrl.h"
////@end includes

/*!
 * Forward declarations
 */

////@begin forward declarations
class wxBoxSizer;
class wxSpinCtrl;
////@end forward declarations

class VirtualBoardChannel;
class RpnHandler;
/*!
 * Control identifiers
 */

////@begin control identifiers
#define ID_VIRTUAL_CHANNEL_DEF_DIALOG 10074
#define SYMBOL_VIRTUALCHANNELDEFDIALOG_STYLE wxCAPTION|wxRESIZE_BORDER|wxSYSTEM_MENU|wxCLOSE_BOX
#define SYMBOL_VIRTUALCHANNELDEFDIALOG_TITLE _("Virtual channel definition")
#define SYMBOL_VIRTUALCHANNELDEFDIALOG_IDNAME ID_VIRTUAL_CHANNEL_DEF_DIALOG
#define SYMBOL_VIRTUALCHANNELDEFDIALOG_SIZE wxSize(550, 250)
#define SYMBOL_VIRTUALCHANNELDEFDIALOG_POSITION wxDefaultPosition
#define ID_VCH_DEF_LEFT_PANEL 11000
#define ID_VCH_DEF_CHANNEL_CHOICE 10079
#define ID_VCH_DEF_ADD_CHANNEL_BUTTON 10080
#define ID_VCH_DEF_CONSTANT_SPINCTRL 10081
#define ID_VCH_DEF_ADD_CONSTANT_BUTTON 10005
#define ID_VCH_DEF_OPERATOR_CHOICE 10006
#define ID_VCH_DEF_ADD_OPERATOR_BUTTON 10007
#define ID_VCH_DEF_REMOVE_BUTTON 10004
#define ID_VCH_DEF_DEFINTION_LISTBOX 10082
#define ID_VCH_MOVE_UP_BUTTON 10000
#define ID_VCH_MOVE_DW_BUTTON 10001
#define ID_VCH_DEF_RIGHT_PANEL 11001
#define ID_VCH_DEF_OK_BUTTON 10078
#define ID_VCH_DEF_CANCEL_BUTTON 10002
#define ID_VCH_DEF_TEST_BUTTON 10003
////@end control identifiers

/*!
 * Compatibility
 */

#ifndef wxCLOSE_BOX
#define wxCLOSE_BOX 0x1000
#endif

/*!
 * VirtualChannelDefDialog class declaration
 */

class VirtualChannelDefDialog: public wxDialog
{    
    DECLARE_DYNAMIC_CLASS( VirtualChannelDefDialog )
    DECLARE_EVENT_TABLE()

public:
    /// Constructors
    VirtualChannelDefDialog( );
    VirtualChannelDefDialog( VirtualBoardChannel* board_channel, wxWindow* parent, wxWindowID id = SYMBOL_VIRTUALCHANNELDEFDIALOG_IDNAME, const wxString& caption = SYMBOL_VIRTUALCHANNELDEFDIALOG_TITLE, const wxPoint& pos = SYMBOL_VIRTUALCHANNELDEFDIALOG_POSITION, const wxSize& size = SYMBOL_VIRTUALCHANNELDEFDIALOG_SIZE, long style = SYMBOL_VIRTUALCHANNELDEFDIALOG_STYLE );

    /// Creation
    bool Create( wxWindow* parent, wxWindowID id = SYMBOL_VIRTUALCHANNELDEFDIALOG_IDNAME, const wxString& caption = SYMBOL_VIRTUALCHANNELDEFDIALOG_TITLE, const wxPoint& pos = SYMBOL_VIRTUALCHANNELDEFDIALOG_POSITION, const wxSize& size = SYMBOL_VIRTUALCHANNELDEFDIALOG_SIZE, long style = SYMBOL_VIRTUALCHANNELDEFDIALOG_STYLE );

    /// Creates the controls and sizers
    void CreateControls();

////@begin VirtualChannelDefDialog event handler declarations

    /// wxEVT_COMMAND_BUTTON_CLICKED event handler for ID_VCH_DEF_ADD_CHANNEL_BUTTON
    void OnVchDefAddChannelButtonClick( wxCommandEvent& event );

    /// wxEVT_COMMAND_BUTTON_CLICKED event handler for ID_VCH_DEF_ADD_CONSTANT_BUTTON
    void OnVchDefAddConstantButtonClick( wxCommandEvent& event );

    /// wxEVT_COMMAND_BUTTON_CLICKED event handler for ID_VCH_DEF_ADD_OPERATOR_BUTTON
    void OnVchDefAddOperatorButtonClick( wxCommandEvent& event );

    /// wxEVT_COMMAND_BUTTON_CLICKED event handler for ID_VCH_DEF_REMOVE_BUTTON
    void OnVchDefRemoveButtonClick( wxCommandEvent& event );

    /// wxEVT_COMMAND_BUTTON_CLICKED event handler for ID_VCH_MOVE_UP_BUTTON
    void OnVchMoveUpButtonClick( wxCommandEvent& event );

    /// wxEVT_COMMAND_BUTTON_CLICKED event handler for ID_VCH_MOVE_DW_BUTTON
    void OnVchMoveDwButtonClick( wxCommandEvent& event );

    /// wxEVT_COMMAND_BUTTON_CLICKED event handler for ID_VCH_DEF_OK_BUTTON
    void OnVchDefOkButtonClick( wxCommandEvent& event );

    /// wxEVT_COMMAND_BUTTON_CLICKED event handler for ID_VCH_DEF_CANCEL_BUTTON
    void OnVchDefCancelButtonClick( wxCommandEvent& event );

    /// wxEVT_COMMAND_BUTTON_CLICKED event handler for ID_VCH_DEF_TEST_BUTTON
    void OnVchDefTestButtonClick( wxCommandEvent& event );

////@end VirtualChannelDefDialog event handler declarations

////@begin VirtualChannelDefDialog member function declarations

    /// Retrieves bitmap resources
    wxBitmap GetBitmapResource( const wxString& name );

    /// Retrieves icon resources
    wxIcon GetIconResource( const wxString& name );
////@end VirtualChannelDefDialog member function declarations

    /// Should we show tooltips?
    static bool ShowToolTips();

////@begin VirtualChannelDefDialog member variables
    wxPanel* m_left_panel;
    wxBoxSizer* m_left_sizer;
    wxChoice* m_channel_ctrl;
    wxSpinCtrl* m_constant_ctrl;
    wxChoice* m_operator_ctrl;
    wxListBox* m_definition_ctrl;
////@end VirtualChannelDefDialog member variables
protected:
	VirtualBoardChannel* m_p_board_channel;
	wxString MakeExpressionDef( void);
};

#endif
    // _VIRTUAL_CHANNEL_DEF_DIALOG_H_
