CAEN V1x90 SDK: cvt_V1190.c File Reference
cvt_V1190.c File Reference
V1190 VME board implementation.
#include <memory.h>
#include <string.h>
#include "cvt_V1190.h"
Functions
BOOL cvt_V1190_open (cvt_V1190_data *p_data, UINT16 base_address, long vme_handle, CVT_V1X90_TYPES type)
V1494 VME boards data initialization.
BOOL cvt_V1190_close (cvt_V1190_data *p_data)
V1190 VME boards closing and resource free.
BOOL cvt_V1190_write_2_micro (cvt_V1190_data *p_data, UINT16 ope_code, const UINT16 *p_params, int num_params)
Writes an opcode to V1190 micro register.
BOOL cvt_V1190_read_from_micro (cvt_V1190_data *p_data, UINT16 ope_code, UINT16 *p_params, int num_params)
Reads an opcode from V1190 micro register.
BOOL cvt_V1190_set_bitmask_control (cvt_V1190_data *p_data, CVT_V1190_CONTROL_MSK value)
Set a bitmask to control register.
BOOL cvt_V1190_clear_bitmask_control (cvt_V1190_data *p_data, CVT_V1190_CONTROL_MSK value)
Clear a bitmask to control 1 register.
BOOL cvt_V1190_set_windows_width (cvt_V1190_data *p_data, UINT16 value)
Set the window width.
BOOL cvt_V1190_set_windows_offset (cvt_V1190_data *p_data, UINT16 value)
Set the window offset.
BOOL cvt_V1190_get_channel_enable (cvt_V1190_data *p_data, UINT16 *p_enable_msk)
Get the channel enable pattern.
BOOL cvt_V1190_set_trigger_match (cvt_V1190_data *p_data)
Set the trigger matching mode.
BOOL cvt_V1190_set_head_trail_enable (cvt_V1190_data *p_data)
Enable TDC Header and Trailer in readout.
BOOL cvt_V1190_set_head_trail_disable (cvt_V1190_data *p_data)
Disable TDC Header and Trailer in readout.
BOOL cvt_V1190_read_MEB (cvt_V1190_data *p_data, void *p_buff, UINT32 *p_buff_size)
Reads data from the Multiple event buffer and stores to user buffer.
BOOL cvt_V1190_set_continuous_acquisition_mode (cvt_V1190_data *p_data, CVT_V1190_EDGE_DETECTION_ENUM edge_detection, CVT_V1190_PAIR_RES_WIDTH_ENUM res_width, const UINT16 *p_enable_msk)
Enable and setups the continuous acquisition mode.
BOOL cvt_V1190_set_trigger_matching_acquisition_mode (cvt_V1190_data *p_data, INT16 window_width, INT16 window_offset, INT16 extra_search_margin, INT16 reject_margin, CVT_V1190_EDGE_DETECTION_ENUM edge_detection, CVT_V1190_PAIR_RES_WIDTH_ENUM res_width, const UINT16 *p_enable_msk, BOOL header_trailer_enable, BOOL empty_event_enable, BOOL trigger_time_tag_enable)
Enable and setups the trigger matching mode.
BOOL cvt_V1190_set_interrupt (cvt_V1190_data *p_data, UINT8 level, UINT8 vector)
Setups interrupt parameters.
BOOL cvt_V1190_set_readout_mode (cvt_V1190_data *p_data, BOOL bus_error_enable, BOOL align64_enable, UINT8 blt_event_number)
Setups data readout mode parameters.
BOOL cvt_V1190_get_status (cvt_V1190_data *p_data, BOOL *p_is_data_ready, BOOL *p_is_term_on, BOOL *p_is_buffer_full, BOOL *p_is_buffer_almost_full, CVT_V1190_STATUS_RES *p_resolution, UINT8 *p_error_bitmask)
Gets information about board status.
BOOL cvt_V1190_get_event_counter (cvt_V1190_data *p_data, UINT32 *p_counter)
Gets the event counter value.
BOOL cvt_V1190_get_event_stored (cvt_V1190_data *p_data, UINT16 *p_counter)
Gets the event stored value.
BOOL cvt_V1190_get_system_info (cvt_V1190_data *p_data, UINT16 *p_firmware_rev, UINT32 *p_tdc_id_buff, UINT16 *p_micro_firmware_rev, UINT16 *p_serial_number)
Gets board's system information.
BOOL cvt_V1190_data_clear (cvt_V1190_data *p_data)
Performs the data clear.
BOOL cvt_V1190_module_reset (cvt_V1190_data *p_data)
Performs the module reset.
BOOL cvt_V1190_set_channel_enable (cvt_V1190_data *p_data, const UINT16 *p_enable_msk)
Set the channel enable mask.
BOOL cvt_V1190_set_almost_full (cvt_V1190_data *p_data, UINT16 almost_full_value)
Sets the almost full level register.
BOOL cvt_V1190_peek_event (cvt_V1190_data *p_data, UINT32 *out_buff, long *p_out_buff_size, UINT32 *p_event_count)
Tries to peek (i.e. copy but not removing) an event from queue and save data to output buffer.
BOOL cvt_V1190_inqueue (cvt_V1190_data *p_data, const UINT32 *in_buff, UINT32 in_buff_size)
Tries to put in_buff_size data word to queue.
BOOL cvt_V1190_dequeue (cvt_V1190_data *p_data, UINT32 *out_buff, UINT32 out_buff_size)
Tries to get out_buff_size data word from the queue.
long cvt_V1190_get_queue_free (cvt_V1190_data *p_data)
Gets the number of free queue space (words).
long cvt_V1190_get_queue_length (cvt_V1190_data *p_data)
Gets the queue length.
BOOL cvt_V1190_set_MCST_CBLT (cvt_V1190_data *p_data, UINT8 address, MCST_CBLT_board_pos pos)
Setups MCST/CBLT parameters this board.
const char * cvt_V1190_SW_rev (void)
Returns the SDK software release.
Detailed Description
V1190 VME board implementation.
Author:
NDA
Version:
1.0
Date:
03/2006
Provides methods, properties and defines to handle V1190 VME boards
Definition in file cvt_V1190.c.
Function Documentation
BOOL cvt_V1190_clear_bitmask_control (cvt_V1190_data * p_data, CVT_V1190_CONTROL_MSK value)
Clear a bitmask to control 1 register.
Clears the bits of the bitmask into the register. The inverted bitmask is ANDed to the actual regiter content
Parameters:
p_data Pointer to board data
value The bitmask to clear: may be a combination of CVT_V1190_CONTROL_MSK bitmask
Returns:
TRUE: Procedure successfully executed
See also:
CVT_V1190_CONTROL_MSK
Definition at line 252 of file cvt_V1190.c.
References cvt_clear_bitmask(), CVT_V1190_CONTROL_ADD, CVT_V1190_CONTROL_AM, CVT_V1190_CONTROL_DATA_SIZE, FALSE, cvt_V1190_data::m_common_data, TRACE, and TRUE.
BOOL cvt_V1190_close (cvt_V1190_data * p_data)
V1190 VME boards closing and resource free.
Provides specific handling for V1190 boards closing.
Parameters:
p_data Pointer to board data
Returns:
TRUE: board successfully closed
Note:
Must be called when done with any other board specific API.
Definition at line 134 of file cvt_V1190.c.
References cvt_board_close(), FALSE, cvt_V1190_data::m_common_data, cvt_V1190_data::m_queue, and TRUE.
BOOL cvt_V1190_data_clear (cvt_V1190_data * p_data)
Performs the data clear.
Writes a dummy value to the software clear register.
Parameters:
p_data Pointer to board data
Returns:
TRUE: Procedure successfully executed
Definition at line 894 of file cvt_V1190.c.
References CVT_V1190_SW_CLEAR_INDEX, cvt_write_reg(), FALSE, cvt_V1190_data::m_common_data, TRACE, and TRUE.
BOOL cvt_V1190_dequeue (cvt_V1190_data * p_data, UINT32 * out_buff, UINT32 out_buff_size)
Tries to get out_buff_size data word from the queue.
Checks for queue available data words and gets data beginning from m_queue_ini. m_queue_ini will be update: if out_buff!= NULL the data will be stored into it.
Parameters:
p_data Pointer to board data
out_buff Pointer to output buffer (may be NULL)
out_buff_size Size of out_buff (UINT32)
Returns:
TRUE: data removed correctly, FALSE elsewhere (e.g. queue underflow)
Definition at line 1083 of file cvt_V1190.c.
References cvt_V1190_get_queue_length(), CVT_V1190_QUEUE_SIZE_DWORD, FALSE, cvt_V1190_data::m_queue, cvt_V1190_data::m_queue_ini, and TRUE.
Referenced by cvt_V1190_peek_event().
BOOL cvt_V1190_get_channel_enable (cvt_V1190_data * p_data, UINT16 * p_enable_msk)
Get the channel enable pattern.
Reads the specified channel enable pattern through micro register opcode.
Parameters:
p_data Pointer to board data
p_enable_msk The channel enable pattern buffer. This is a user allocated buffer, providing storage for CVT_V1190_NUM_TDC_A*2, CVT_V1190_NUM_TDC_B*2, CVT_V1290_NUM_TDC_A/2, CVT_V1290_NUM_TDC_N/2 according to board type (CVT_V1X90_TYPES)
Returns:
TRUE: Procedure successfully executed
< The board is V1190A
< The board is V1190B
< The board is V1290A
< The board is V1290N
Definition at line 301 of file cvt_V1190.c.
References CVT_V1190_CH_PER_TDC, CVT_V1190_NUM_TDC_A, CVT_V1190_NUM_TDC_B, CVT_V1190_READ_EN_PATTERN_OPCODE, cvt_V1190_read_from_micro(), CVT_V1190_TYPE_A, CVT_V1190_TYPE_B, CVT_V1290_CH_PER_TDC, CVT_V1290_NUM_TDC_A, CVT_V1290_NUM_TDC_N, CVT_V1290_TYPE_A, CVT_V1290_TYPE_N, FALSE, cvt_V1190_data::m_type, TRACE, TRACE1, and TRUE.
BOOL cvt_V1190_get_event_counter (cvt_V1190_data * p_data, UINT32 * p_counter)
Gets the event counter value.
Gets the event counter actual value.
Parameters:
p_data Pointer to board data
p_counter Pointer to the counter value.
Returns:
TRUE: Procedure successfully executed
Definition at line 785 of file cvt_V1190.c.
References cvt_read_reg(), CVT_V1190_EVENT_COUNTER_INDEX, FALSE, cvt_V1190_data::m_common_data, TRACE, and TRUE.
BOOL cvt_V1190_get_event_stored (cvt_V1190_data * p_data, UINT16 * p_counter)
Gets the event stored value.
Gets the event stored actual value.
Parameters:
p_data Pointer to board data
p_counter Pointer to the counter value.
Returns:
TRUE: Procedure successfully executed
Definition at line 803 of file cvt_V1190.c.
References cvt_read_reg(), CVT_V1190_EVENT_STORED_INDEX, FALSE, cvt_V1190_data::m_common_data, TRACE, and TRUE.
long cvt_V1190_get_queue_free (cvt_V1190_data * p_data)
Gets the number of free queue space (words).
Parameters:
p_data Pointer to board data
Returns:
The number of free queue space (UINT32 words)
Definition at line 1117 of file cvt_V1190.c.
References CVT_V1190_QUEUE_SIZE_DWORD, cvt_V1190_data::m_queue_end, and cvt_V1190_data::m_queue_ini.
Referenced by cvt_V1190_inqueue().
long cvt_V1190_get_queue_length (cvt_V1190_data * p_data)
Gets the queue length.
Parameters:
p_data Pointer to board data
Returns:
The queue length (UINT32 words)
Definition at line 1125 of file cvt_V1190.c.
References CVT_V1190_QUEUE_SIZE_DWORD, cvt_V1190_data::m_queue_end, and cvt_V1190_data::m_queue_ini.
Referenced by cvt_V1190_dequeue().
BOOL cvt_V1190_get_status (cvt_V1190_data * p_data, BOOL * p_is_data_ready, BOOL * p_is_term_on, BOOL * p_is_buffer_full, BOOL * p_is_buffer_almost_full, CVT_V1190_STATUS_RES * p_resolution, UINT8 * p_error_bitmask)
Gets information about board status.
Parameters:
p_data Pointer to board data
p_is_data_ready Returns TRUE if data is ready.
p_is_term_on Returns TRUE if term bit is on.
p_is_buffer_full Returns TRUE if buffer is full.
p_is_buffer_almost_full Returns TRUE if buffer is almost full.
p_resolution Returns the resolution
p_error_bitmask Returns the TDC bitmask error: if bit i is 1 then the TDCi is on error
Returns:
TRUE: Procedure successfully executed
Definition at line 761 of file cvt_V1190.c.
References cvt_read_reg(), CVT_V1190_GET_STATUS_ERROR, CVT_V1190_GET_STATUS_RES, CVT_V1190_STATUS_INDEX, CVT_V1190_STS_ALMOST_FULL_MSK, CVT_V1190_STS_DREADY_MSK, CVT_V1190_STS_FULL_MSK, CVT_V1190_STS_TERM_ON_MSK, FALSE, cvt_V1190_data::m_common_data, TRACE, and TRUE.
BOOL cvt_V1190_get_system_info (cvt_V1190_data * p_data, UINT16 * p_firmware_rev, UINT32 * p_tdc_id_buff, UINT16 * p_micro_firmware_rev, UINT16 * p_serial_number)
Gets board's system information.
Reads the firmware revision register, TDC revs etc.
Parameters:
p_data Pointer to board data
p_firmware_rev The firmware release (MSB major release, LSB minor release).
p_tdc_id_buff The TDC IDs buffer This is a user allocated buffer, providing storage for CVT_V1190_NUM_TDC_# words according to the board type (CVT_V1X90_TYPES). p_tdc_id_buff[#] format is: MSB major release, LSB minor release.
p_micro_firmware_rev The micro firmware release (MSB major release, LSB minor release).
p_serial_number The serial number.
Returns:
TRUE: Procedure successfully executed
< The board is V1190A
< The board is V1190B
< The board is V1290A
< The board is V1290N
Definition at line 822 of file cvt_V1190.c.
References cvt_read_reg(), CVT_V1190_FW_REV_INDEX, CVT_V1190_NUM_TDC_A, CVT_V1190_NUM_TDC_B, cvt_V1190_read_from_micro(), CVT_V1190_READ_MICRO_REV_OPCODE, CVT_V1190_READ_TDC_ID_OPCODE, CVT_V1190_ROM_SERIAL_0_INDEX, CVT_V1190_ROM_SERIAL_1_INDEX, CVT_V1190_TYPE_A, CVT_V1190_TYPE_B, CVT_V1290_NUM_TDC_A, CVT_V1290_NUM_TDC_N, CVT_V1290_TYPE_A, CVT_V1290_TYPE_N, FALSE, cvt_V1190_data::m_common_data, cvt_V1190_data::m_type, TRACE, TRACE1, and TRUE.
BOOL cvt_V1190_inqueue (cvt_V1190_data * p_data, const UINT32 * in_buff, UINT32 in_buff_size)
Tries to put in_buff_size data word to queue.
Checks for the queue available free words and stores data beginning from m_queue_end. m_queue_end will be update
Parameters:
p_data Pointer to board data
in_buff Pointer to input buffer
in_buff_size Size of in_buff (UINT32)
Returns:
TRUE: data stored correctly FALSE elsewhere (e.g. queue overflow)
Definition at line 1055 of file cvt_V1190.c.
References cvt_V1190_get_queue_free(), CVT_V1190_QUEUE_SIZE_DWORD, FALSE, cvt_V1190_data::m_queue, cvt_V1190_data::m_queue_end, and TRUE.
BOOL cvt_V1190_module_reset (cvt_V1190_data * p_data)
Performs the module reset.
Writes a dummy value to the module reset register.
Parameters:
p_data Pointer to board data
Returns:
TRUE: Procedure successfully executed
Definition at line 909 of file cvt_V1190.c.
References CVT_V1190_MOD_RESET_INDEX, cvt_write_reg(), FALSE, cvt_V1190_data::m_common_data, TRACE, and TRUE.
BOOL cvt_V1190_open (cvt_V1190_data * p_data, UINT16 base_address, long vme_handle, CVT_V1X90_TYPES type)
V1494 VME boards data initialization.
Provides specific handling for V495 boards opening.
Parameters:
p_data Pointer to board data
base_address The board base address (MSW)
vme_handle The VME handle
type The board type : it must be a CVT_V1X90_TYPES value
Returns:
TRUE: board successfully opened
Note:
Must be called before any other board specific API.
See also:
CVT_V1X90_TYPES
< The board is V1190A
< The board is V1190B
< The board is V1290A
< The board is V1290N
Definition at line 96 of file cvt_V1190.c.
References cvt_board_open(), CVT_V1190_QUEUE_SIZE_DWORD, cvt_V1190_set_MCST_CBLT(), CVT_V1190_TYPE_A, CVT_V1190_TYPE_B, CVT_V1290_TYPE_A, CVT_V1290_TYPE_N, FALSE, cvt_V1190_data::m_common_data, cvt_V1190_data::m_queue, cvt_V1190_data::m_type, cvt_board_data::set_MCST_CBLT, TRACE, TRACE1, and TRUE.
BOOL cvt_V1190_peek_event (cvt_V1190_data * p_data, UINT32 * out_buff, long * p_out_buff_size, UINT32 * p_event_count)
Tries to peek (i.e. copy but not removing) an event from queue and save data to output buffer.
Scans the queue beginning from m_queue_ini, searching for an event block, and stores data output stream.
Parameters:
p_data Pointer to board data
out_buff Pointer to output buffer
p_out_buff_size Size of out_buff (UINT32). The number of data written into out_buff (UINT32) on exit.
p_event_count The found event count
Returns:
TRUE: some event found, FALSE elsewhere
Definition at line 977 of file cvt_V1190.c.
References cvt_V1190_dequeue(), CVT_V1190_GET_GLB_HDR_EVENT_COUNT, CVT_V1190_IS_GLOBAL_HEADER, CVT_V1190_IS_GLOBAL_TRAILER, CVT_V1190_QUEUE_SIZE_DWORD, FALSE, cvt_V1190_data::m_queue, cvt_V1190_data::m_queue_end, cvt_V1190_data::m_queue_ini, and TRUE.
BOOL cvt_V1190_read_from_micro (cvt_V1190_data * p_data, UINT16 ope_code, UINT16 * p_params, int num_params)
Reads an opcode from V1190 micro register.
Reads an opcode to V1190 micro register and the specified number of parameters. Handles all the necessary handshake with micro to get the job done.
Parameters:
p_data Pointer to board data
ope_code The ope code to read
p_params Pointer to parameter buffer (caller allocated). May be NULL if num_params== 0
num_params The number of parameters to read
Returns:
TRUE: Opcode read successfull
Definition at line 199 of file cvt_V1190.c.
References cvt_read_reg(), CVT_V1190_MICRO_HND_INDEX, CVT_V1190_MICRO_HND_READOK_MSK, CVT_V1190_MICRO_HND_WRITEOK_MSK, CVT_V1190_MICRO_INDEX, cvt_write_reg(), FALSE, cvt_V1190_data::m_common_data, and TRUE.
Referenced by cvt_V1190_get_channel_enable(), and cvt_V1190_get_system_info().
BOOL cvt_V1190_read_MEB (cvt_V1190_data * p_data, void * p_buff, UINT32 * p_buff_size)
Reads data from the Multiple event buffer and stores to user buffer.
Call cvt_FIFO_BLT_read for Multiple event buffer and stores data into user buffer. If the returned data is just a V1190 filler, this is discarded.
Parameters:
p_data Pointer to board data
p_buff The target buffer: caller allocated
p_buff_size The buffer size (bytes). On exit will holds the number of bytes really read. If just a filler data will be read this will be discarded
Returns:
TRUE: Procedure successfully executed
See also:
cvt_FIFO_BLT_read
Definition at line 376 of file cvt_V1190.c.
References cvt_FIFO_BLT_read(), CVT_V1190_IS_FILLER, CVT_V1190_OUT_BUFFER_ADD, CVT_V1190_OUT_BUFFER_AM, CVT_V1190_OUT_BUFFER_DATA_SIZE, FALSE, cvt_V1190_data::m_common_data, and TRUE.
BOOL cvt_V1190_set_almost_full (cvt_V1190_data * p_data, UINT16 almost_full_value)
Sets the almost full level register.
Writes the specified value into the almost full level register. This Register allows the User to set the Almost Full Level of the Output Buffer. When the Output Buffer contains a number of words at least equal to the Almost Full Level, then an Interrupt Request (IRQ) is generated (if enabled) and the related bit in the Status Register is set.
Parameters:
p_data Pointer to board data
almost_full_value The almost full level value.
Returns:
TRUE: Procedure successfully executed
Definition at line 959 of file cvt_V1190.c.
References CVT_V1190_ALMOST_FULL_LVL_INDEX, cvt_write_reg(), FALSE, cvt_V1190_data::m_common_data, TRACE, and TRUE.
BOOL cvt_V1190_set_bitmask_control (cvt_V1190_data * p_data, CVT_V1190_CONTROL_MSK value)
Set a bitmask to control register.
Sets the bits of the bitmask into the register. The bitmask is ORed to the actual regiter content
Parameters:
p_data Pointer to board data
value The bitmask to set : may be a combination of CVT_V1190_CONTROL_MSK bitmask
Returns:
TRUE: Procedure successfully executed
See also:
CVT_V1190_CONTROL_MSK
Definition at line 237 of file cvt_V1190.c.
References cvt_set_bitmask(), CVT_V1190_CONTROL_ADD, CVT_V1190_CONTROL_AM, CVT_V1190_CONTROL_DATA_SIZE, FALSE, cvt_V1190_data::m_common_data, TRACE, and TRUE.
BOOL cvt_V1190_set_channel_enable (cvt_V1190_data * p_data, const UINT16 * p_enable_msk)
Set the channel enable mask.
Writes the specified channel enable pattern through micro register opcode.
Parameters:
p_data Pointer to board data
p_enable_msk The enable masks' array. This is a user allocated buffer, providing storage for CVT_V1190_NUM_TDC_A*2, CVT_V1190_NUM_TDC_B*2, CVT_V1290_NUM_TDC_A/2, CVT_V1290_NUM_TDC_N/2 according to board type (CVT_V1X90_TYPES)
Returns:
TRUE: Procedure successfully executed
< The board is V1190A
< The board is V1190B
< The board is V1290A
< The board is V1290A
Definition at line 923 of file cvt_V1190.c.
References CVT_V1190_CH_PER_TDC, CVT_V1190_NUM_TDC_A, CVT_V1190_NUM_TDC_B, CVT_V1190_TYPE_A, CVT_V1190_TYPE_B, cvt_V1190_write_2_micro(), CVT_V1190_WRITE_EN_PATTERN_OPCODE, CVT_V1290_CH_PER_TDC, CVT_V1290_NUM_TDC_A, CVT_V1290_NUM_TDC_N, CVT_V1290_TYPE_A, CVT_V1290_TYPE_N, FALSE, cvt_V1190_data::m_type, TRACE, TRACE1, and TRUE.
Referenced by cvt_V1190_set_continuous_acquisition_mode(), and cvt_V1190_set_trigger_matching_acquisition_mode().
BOOL cvt_V1190_set_continuous_acquisition_mode (cvt_V1190_data * p_data, CVT_V1190_EDGE_DETECTION_ENUM edge_detection, CVT_V1190_PAIR_RES_WIDTH_ENUM res_width, const UINT16 * p_enable_msk)
Enable and setups the continuous acquisition mode.
Setups the relevant parameters for continuous acquisition mode.
Parameters:
p_data Pointer to board data
edge_detection The edge detection type. Must be a valid CVT_V1190_EDGE_DETECTION_ENUM
res_width The resolution width. Must be a valid CVT_V1190_PAIR_RES_WIDTH_ENUM This parameter is ignored for V1290X boards
p_enable_msk The channel enable pattern buffer. This is a user allocated buffer, providing storage for CVT_V1190_NUM_TDC_A*2, CVT_V1190_NUM_TDC_B*2, CVT_V1290_NUM_TDC_A/2, CVT_V1290_NUM_TDC_N/2 according to board type (CVT_V1X90_TYPES) It may be NULL (i.e. if you don't need to setup channel enable patterns).
Returns:
TRUE: Procedure successfully executed
See also:
CVT_V1190_EDGE_DETECTION_ENUM
CVT_V1190_PAIR_RES_WIDTH_ENUM
< Pair mode.
< The board is V1190A
< The board is V1190B
< The board is V1290A
< The board is V1290N
< Trailing only.
< Leading only.
< Trailing and Leading.
< The board is V1190A
< The board is V1190B
< 100 ps.
< 200 ps.
< 400 ps.
< 800 ps.
< 1.6 ns.
< 3.12 ns.
< 6.25 ns.
< 12.5 ns.
< 25 ns.
< 50 ns.
< 100 ns.
< 200 ns.
< 400 ns.
< 800 ns.
< The board is V1290A
< The board is V1290N
Definition at line 395 of file cvt_V1190.c.
References CVT_V1190_CONT_STORE_OPCODE, CVT_V1190_ED_LEADING_ONLY, CVT_V1190_ED_PAIR_MODE, CVT_V1190_ED_TRAILING_AND_LEADING, CVT_V1190_ED_TRAILING_ONLY, CVT_V1190_PRW_100NS, CVT_V1190_PRW_100PS, CVT_V1190_PRW_12_5NS, CVT_V1190_PRW_1_6NS, CVT_V1190_PRW_200NS, CVT_V1190_PRW_200PS, CVT_V1190_PRW_25NS, CVT_V1190_PRW_3_12NS, CVT_V1190_PRW_400NS, CVT_V1190_PRW_400PS, CVT_V1190_PRW_50NS, CVT_V1190_PRW_6_25NS, CVT_V1190_PRW_800NS, CVT_V1190_PRW_800PS, cvt_V1190_set_channel_enable(), CVT_V1190_SET_DETECTION_OPCODE, CVT_V1190_SET_PAIR_RES_OPCODE, CVT_V1190_SET_PAIR_RES_WITH, CVT_V1190_TYPE_A, CVT_V1190_TYPE_B, cvt_V1190_write_2_micro(), CVT_V1290_TYPE_A, CVT_V1290_TYPE_N, FALSE, cvt_V1190_data::m_type, TRACE, TRACE1, and TRUE.
BOOL cvt_V1190_set_head_trail_disable (cvt_V1190_data * p_data)
Disable TDC Header and Trailer in readout.
Writes through micro register opcode to disable TDC Header and Trailer in readout.
Parameters:
p_data Pointer to board data
Returns:
TRUE: Procedure successfully executed
Definition at line 363 of file cvt_V1190.c.
References CVT_V1190_DIS_HEAD_TRAILER_OPCODE, cvt_V1190_write_2_micro(), FALSE, TRACE, and TRUE.
BOOL cvt_V1190_set_head_trail_enable (cvt_V1190_data * p_data)
Enable TDC Header and Trailer in readout.
Writes through micro register opcode to enable TDC Header and Trailer in readout.
Parameters:
p_data Pointer to board data
Returns:
TRUE: Procedure successfully executed
Definition at line 350 of file cvt_V1190.c.
References CVT_V1190_EN_HEAD_TRAILER_OPCODE, cvt_V1190_write_2_micro(), FALSE, TRACE, and TRUE.
BOOL cvt_V1190_set_interrupt (cvt_V1190_data * p_data, UINT8 level, UINT8 vector)
Setups interrupt parameters.
Setups the relevant parameters for interrupt usage.
Parameters:
p_data Pointer to board data
level The interrupt level.
vector The interrupt vector.
Returns:
TRUE: Procedure successfully executed
Definition at line 678 of file cvt_V1190.c.
References CVT_V1190_INT_LEVEL_INDEX, CVT_V1190_INT_VECTOR_INDEX, cvt_write_reg(), FALSE, cvt_V1190_data::m_common_data, TRACE, and TRUE.
BOOL cvt_V1190_set_MCST_CBLT (cvt_V1190_data * p_data, UINT8 address, MCST_CBLT_board_pos pos)
Setups MCST/CBLT parameters this board.
Setups the relevant parameters for MCST/CBLT usage.
Parameters:
p_data Pointer to board data.
address The MCST/CBLT address.
pos The board position into the MCST / CBLT chain: it must be a MCST_CBLT_board_pos identifier
Returns:
TRUE: Procedure successfully executed
See also:
MCST_CBLT_board_pos
Definition at line 1133 of file cvt_V1190.c.
References CVT_V1190_MCCTRL_DISABLED_BOARD_MSK, CVT_V1190_MCCTRL_FIRST_BOARD_MSK, CVT_V1190_MCCTRL_LAST_BOARD_MSK, CVT_V1190_MCCTRL_MID_BOARD_MSK, CVT_V1190_MCST_CBLT_ADDRESS_INDEX, CVT_V1190_MCST_CBLT_CTRL_INDEX, cvt_write_reg(), FALSE, cvt_V1190_data::m_common_data, MCST_CBLT_board_disabled, MCST_CBLT_board_pos_first, MCST_CBLT_board_pos_last, MCST_CBLT_board_pos_mid, TRACE, TRACE1, and TRUE.
Referenced by cvt_V1190_open().
BOOL cvt_V1190_set_readout_mode (cvt_V1190_data * p_data, BOOL bus_error_enable, BOOL align64_enable, UINT8 blt_event_number)
Setups data readout mode parameters.
Setups the relevant parameters for data readout.
Parameters:
p_data Pointer to board data
bus_error_enable Enable bus error: the module is enabled to generate a Bus error to finish a block transfer.
align64_enable Enable align 64: the module is enabled to add dummy word when the number of words is odd.
blt_event_number The number of complete events to transfer via BLT
Returns:
TRUE: Procedure successfully executed
Definition at line 709 of file cvt_V1190.c.
References cvt_clear_bitmask_reg(), cvt_set_bitmask_reg(), CVT_V1190_BLT_EVENT_NUM_INDEX, CVT_V1190_CONTROL_INDEX, CVT_V1190_CTRL_ALIGN64_MSK, CVT_V1190_CTRL_BERR_ENABLE_MSK, cvt_write_reg(), FALSE, cvt_V1190_data::m_common_data, TRACE, and TRUE.
BOOL cvt_V1190_set_trigger_match (cvt_V1190_data * p_data)
Set the trigger matching mode.
Writes dummy value through micro register opcode to set the trigger matching mode.
Parameters:
p_data Pointer to board data
Returns:
TRUE: Procedure successfully executed
Definition at line 337 of file cvt_V1190.c.
References CVT_V1190_TRG_MATCH_OPCODE, cvt_V1190_write_2_micro(), FALSE, TRACE, and TRUE.
BOOL cvt_V1190_set_trigger_matching_acquisition_mode (cvt_V1190_data * p_data, INT16 window_width, INT16 window_offset, INT16 extra_search_margin, INT16 reject_margin, CVT_V1190_EDGE_DETECTION_ENUM edge_detection, CVT_V1190_PAIR_RES_WIDTH_ENUM res_width, const UINT16 * p_enable_msk, BOOL header_trailer_enable, BOOL empty_event_enable, BOOL trigger_time_tag_enable)
Enable and setups the trigger matching mode.
Setups the relevant parameters for trigger matching mode usage.
Parameters:
p_data Pointer to board data
window_width Sets the width of the match window (a negative value means don't change).
window_offset Sets the offset of the match window with respect to the trigger itself (a negative value means don't change)
extra_search_margin Sets the extra search field of the match window (a negative value means don't change).
reject_margin Sets the reject margin, expressed in clock cycles (a negative value means don't change).
edge_detection The edge detection type. Must be a valid CVT_V1190_EDGE_DETECTION_ENUM
res_width The resolution width. Must be a valid CVT_V1190_PAIR_RES_WIDTH_ENUM This parameter is ignored for V1290X boards
p_enable_msk The channel enable pattern buffer. This is a user allocated buffer, providing storage for CVT_V1190_NUM_TDC_A*2, CVT_V1190_NUM_TDC_B*2, CVT_V1290_NUM_TDC_A/2, CVT_V1290_NUM_TDC_N/2 according to board type (CVT_V1X90_TYPES) It may be NULL (i.e. if you don't need to setup channel enable patterns).
header_trailer_enable Enable/disable header and trailer.
empty_event_enable Enable/disable empty event storage.
trigger_time_tag_enable Enable/disable the trigger time tag.
Returns:
TRUE: Procedure successfully executed
< Pair mode.
< The board is V1190A
< The board is V1190B
< The board is V1290A
< The board is V1290N
< Trailing only.
< Leading only.
< Trailing and Leading.
< The board is V1190A
< The board is V1190B
< 100 ps.
< 200 ps.
< 400 ps.
< 800 ps.
< 1.6 ns.
< 3.12 ns.
< 6.25 ns.
< 12.5 ns.
< 25 ns.
< 50 ns.
< 100 ns.
< 200 ns.
< 400 ns.
< 800 ns.
< The board is V1290A
< The board is V1290N
Definition at line 493 of file cvt_V1190.c.
References cvt_clear_bitmask_reg(), cvt_set_bitmask_reg(), CVT_V1190_CONTROL_INDEX, CVT_V1190_CTRL_EMPTY_EVENT_MSK, CVT_V1190_CTRL_TRIGGER_TIME_TAG_ENABLE_MSK, CVT_V1190_DIS_HEAD_TRAILER_OPCODE, CVT_V1190_ED_LEADING_ONLY, CVT_V1190_ED_PAIR_MODE, CVT_V1190_ED_TRAILING_AND_LEADING, CVT_V1190_ED_TRAILING_ONLY, CVT_V1190_EN_HEAD_TRAILER_OPCODE, CVT_V1190_PRW_100NS, CVT_V1190_PRW_100PS, CVT_V1190_PRW_12_5NS, CVT_V1190_PRW_1_6NS, CVT_V1190_PRW_200NS, CVT_V1190_PRW_200PS, CVT_V1190_PRW_25NS, CVT_V1190_PRW_3_12NS, CVT_V1190_PRW_400NS, CVT_V1190_PRW_400PS, CVT_V1190_PRW_50NS, CVT_V1190_PRW_6_25NS, CVT_V1190_PRW_800NS, CVT_V1190_PRW_800PS, cvt_V1190_set_channel_enable(), CVT_V1190_SET_DETECTION_OPCODE, CVT_V1190_SET_PAIR_RES_OPCODE, CVT_V1190_SET_PAIR_RES_WITH, CVT_V1190_SET_REJ_MARGIN_OPCODE, CVT_V1190_SET_SW_MARGIN_OPCODE, CVT_V1190_SET_WIN_OFFSET_OPCODE, CVT_V1190_SET_WIN_WIDTH_OPCODE, CVT_V1190_TRG_MATCH_OPCODE, CVT_V1190_TYPE_A, CVT_V1190_TYPE_B, cvt_V1190_write_2_micro(), CVT_V1290_TYPE_A, CVT_V1290_TYPE_N, FALSE, cvt_V1190_data::m_common_data, cvt_V1190_data::m_type, TRACE, TRACE1, and TRUE.
BOOL cvt_V1190_set_windows_offset (cvt_V1190_data * p_data, UINT16 value)
Set the window offset.
Writes the specified value through micro register opcode.
Parameters:
p_data Pointer to board data
value The value to set
Returns:
TRUE: Procedure successfully executed
Definition at line 287 of file cvt_V1190.c.
References CVT_V1190_SET_WIN_OFFSET_OPCODE, cvt_V1190_write_2_micro(), FALSE, TRACE, and TRUE.
BOOL cvt_V1190_set_windows_width (cvt_V1190_data * p_data, UINT16 value)
Set the window width.
Writes the specified value through micro register opcode.
Parameters:
p_data Pointer to board data
value The value to set
Returns:
TRUE: Procedure successfully executed
Definition at line 273 of file cvt_V1190.c.
References CVT_V1190_SET_WIN_WIDTH_OPCODE, cvt_V1190_write_2_micro(), FALSE, TRACE, and TRUE.
const char * cvt_V1190_SW_rev (void)
Returns the SDK software release.
Returns:
const char*: The SDK revision string
Definition at line 1181 of file cvt_V1190.c.
BOOL cvt_V1190_write_2_micro (cvt_V1190_data * p_data, UINT16 ope_code, const UINT16 * p_params, int num_params)
Writes an opcode to V1190 micro register.
Writes an opcode to V1190 micro register and the specified number of parameters. Handles all the necessary handshake with micro to get the job done.
Parameters:
p_data Pointer to board data
ope_code The ope code to write
p_params Pointer to parameter buffer (caller allocated). May be NULL if num_params== 0
num_params The number of parameters to write
Returns:
TRUE: Opcode write successfull
Definition at line 161 of file cvt_V1190.c.
References cvt_read_reg(), CVT_V1190_MICRO_HND_INDEX, CVT_V1190_MICRO_HND_WRITEOK_MSK, CVT_V1190_MICRO_INDEX, cvt_write_reg(), FALSE, cvt_V1190_data::m_common_data, and TRUE.
Referenced by cvt_V1190_set_channel_enable(), cvt_V1190_set_continuous_acquisition_mode(), cvt_V1190_set_head_trail_disable(), cvt_V1190_set_head_trail_enable(), cvt_V1190_set_trigger_match(), cvt_V1190_set_trigger_matching_acquisition_mode(), cvt_V1190_set_windows_offset(), and cvt_V1190_set_windows_width().