/////////////////////////////////////////////////////////////////////////////
// Name:        drawing_canvas.h
// Purpose:     
// Author:      NDA
// Modified by: 
// Created:     10/10/2006 15:08:09
// RCS-ID:      
// Copyright:   CAEN S.p.A All rights reserved.
// Licence:     
/////////////////////////////////////////////////////////////////////////////

// Generated by DialogBlocks (unregistered), 10/10/2006 15:08:09

#ifndef _DRAWING_CANVAS_H_
#define _DRAWING_CANVAS_H_

#if defined(__GNUG__) && !defined(NO_GCC_PRAGMA)
#pragma interface "drawing_canvas.h"
#endif

/*!
 * Includes
 */

////@begin includes
////@end includes

/*!
 * Forward declarations
 */

////@begin forward declarations
////@end forward declarations

class DrawingPanel;

/*!
 * Control identifiers
 */

////@begin control identifiers
#define ID_DRAWING_CANVAS_DIALOG 10026
#define SYMBOL_DRAWINGCANVAS_STYLE 0
#define SYMBOL_DRAWINGCANVAS_TITLE _("DrawingCanvas")
#define SYMBOL_DRAWINGCANVAS_IDNAME ID_DRAWING_CANVAS_DIALOG
#define SYMBOL_DRAWINGCANVAS_SIZE wxSize(400, 300)
#define SYMBOL_DRAWINGCANVAS_POSITION wxDefaultPosition
////@end control identifiers

/*!
 * Compatibility
 */

#ifndef wxCLOSE_BOX
#define wxCLOSE_BOX 0x1000
#endif

/*!
 * DrawingCanvas class declaration
 */

class DrawingCanvas: public wxPanel
{    
    DECLARE_DYNAMIC_CLASS( DrawingCanvas )
    DECLARE_EVENT_TABLE()

public:
    /// Constructors
    DrawingCanvas( );
    DrawingCanvas( int scope_index, wxWindow* parent, wxWindowID id = SYMBOL_DRAWINGCANVAS_IDNAME, const wxPoint& pos = SYMBOL_DRAWINGCANVAS_POSITION, const wxSize& size = SYMBOL_DRAWINGCANVAS_SIZE, long style = SYMBOL_DRAWINGCANVAS_STYLE );
	~DrawingCanvas( );
    /// Creation
    bool Create( wxWindow* parent, wxWindowID id = SYMBOL_DRAWINGCANVAS_IDNAME, const wxPoint& pos = SYMBOL_DRAWINGCANVAS_POSITION, const wxSize& size = SYMBOL_DRAWINGCANVAS_SIZE, long style = SYMBOL_DRAWINGCANVAS_STYLE );

    /// Creates the controls and sizers
    void CreateControls();

////@begin DrawingCanvas event handler declarations
    /// wxEVT_SIZE event handler for ID_DRAWING_CANVAS_DIALOG
    void OnSize( wxSizeEvent& event );

    /// wxEVT_PAINT event handler for ID_DRAWING_CANVAS_DIALOG
    void OnPaint( wxPaintEvent& event );

    /// wxEVT_ERASE_BACKGROUND event handler for ID_DRAWING_CANVAS_DIALOG
    void OnEraseBackground( wxEraseEvent& event );

////@end DrawingCanvas event handler declarations

////@begin DrawingCanvas member function declarations
    /// Retrieves bitmap resources
    wxBitmap GetBitmapResource( const wxString& name );

    /// Retrieves icon resources
    wxIcon GetIconResource( const wxString& name );
////@end DrawingCanvas member function declarations

    /// Should we show tooltips?
    static bool ShowToolTips();

////@begin DrawingCanvas member variables
////@end DrawingCanvas member variables
public:
	void RefreshBackBitmap( void);
	void RefreshSampleBitmap( wxBitmap *p_sample_bitmap);
	static const int NUM_DIV_PER_SCREEN= 10;
protected:
	void DrawGrid( wxDC &dc);
	void DrawBackground( wxDC &dc);
	void DrawCursor( wxDC &dc);
	void DrawTrigger( wxDC &dc);
	void DrawSamples( wxDC &dc);

	wxBitmap *m_p_back_bitmap, *m_p_buffer_bitmap;
	DrawingPanel *m_parent;
	int m_pix_X, m_pix_Y;
	bool m_first_time;
	int m_scope_index;

};

#endif
    // _DRAWING_CANVAS_H_
